export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  CREATE_ADMIN: "CREATE_ADMIN",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  UPDATE_EXCHANGE_RATE: "UPDATE_EXCHANGE_RATE",
  IMPORT_NRB_RATE: "IMPORT_NRB_RATE",
  CREATE_BRANCH: "CREATE_BRANCH",
  UPDATE_BRANCH: "UPDATE_BRANCH",
  DELETE_BRANCH: "DELETE_BRANCH",
  PUBLISH_NEWS: "PUBLISH_NEWS",
  UPDATE_WEBSITE: "UPDATE_WEBSITE",
  CHANGE_SETTINGS: "CHANGE_SETTINGS",
  UPLOAD_MEDIA: "UPLOAD_MEDIA",
  DELETE_MEDIA: "DELETE_MEDIA",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
